sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy-5.6.0"
install:
  - pip install -r requirements.txt
  - pip install requests[security]
  - pip install pytest-cov
  - pip install coveralls
script:
  - py.test --cov pagarme
after_success:
  - coveralls
