sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3"
install:
  - python setup.py install
  - pip install -r requirements-dev.txt
after_success:
  - coveralls
